env = Environment()

env['APP_TARGET'] = 'SimpleReceiverApp'
env['APP_SOURCES'] = ['SimpleReceiverApp.cpp']

env = SConscript('../../../scons/SConscript', exports = 'env')

SConscript('../../../../../scons/SConscript', exports = 'env')
